python train.py \
  --pretrained_model_name_or_path="claudiom4sir/StableVSR" \
  --pretrained_vae_model_name_or_path="claudiom4sir/StableVSR" \
  --controlnet_model_name_or_path="/path/to/controlnet/" \
  --unet_model_name_or_path="/path/to/unet/" \
  --output_dir="/path/to/output/" \
  --logging_dir="/path/to/output/logs/" \
  --dataset_config_path="./dataset/REDS/config_test.yaml" \
  --degradation_params_json ./degradation/degradation_params.json \
  --G_lr=1e-5 \
  --D_lr=1e-5 \
  --validation_steps=1000 \
  --train_batch_size=4 \
  --adv_weight=0.05 \
  --tlpips_weight=0.1 \
  --num_ts=4 \
  --dataloader_num_workers=8 \
  --max_train_steps=40000 \
  --checkpointing_steps=1000 \
  --train_unet \
  --train_controlnet \
  --of_model="DRFA"
