dataset:
  train:
    dataroot_gt: /path/to/REDS/train/
    dataroot_lq: /path/to/REDS-BI/train/
    meta_info_file: ./dataset/REDS/train_metadata.txt
    dataroot_flow:
    io_backend:
      type: disk
    num_frame: 3
    test_mode: False
    interval_list: [1]
    random_reverse: False
    gt_size: 256
    use_hflip: True
    use_rot: False
    scale: 4
    remove_partition: False
  test:
    dataroot_gt: /path/to/REDS/val-10/
    dataroot_lq: /path/to/REDS-BI/val-10/
    meta_info_file: ./dataset/REDS/valid_metadata.txt
    io_backend:
      type: disk
    num_frame: 3
    test_mode: True
    interval_list: [1]
    random_reverse: False
    gt_size: 256
    use_hflip: False
    use_rot: False
    scale: 4